import { Hospital, Department, SpecialistDoctor, PatientJourney, Prescription, SMSAlert } from '@/types';

export const MOCK_HOSPITALS: Hospital[] = [
  {
    id: 'sinnar',
    name: {
      mr: 'ग्रामीण रुग्णालय, सिन्नर (नाशिक)',
      hi: 'ग्रामीण अस्पताल, सिन्नर (नाशिक)',
      en: 'Rural Hospital, Sinnar (Nashik)',
    },
    district: 'Nashik',
    location: 'Sinnar-Shirdi Highway, Sinnar',
    contactNumber: '0253-252110',
    emergencyPhone: '108 / 0253-252112',
    totalActivePatients: 42,
  },
  {
    id: 'igatpuri',
    name: {
      mr: 'उपजिल्हा रुग्णालय, इगतपुरी',
      hi: 'उपजिला अस्पताल, इगतपुरी',
      en: 'Sub-District Hospital, Igatpuri',
    },
    district: 'Nashik',
    location: 'Mumbai-Agra Highway, Igatpuri',
    contactNumber: '02553-244021',
    emergencyPhone: '108',
    totalActivePatients: 28,
  },
  {
    id: 'dindori',
    name: {
      mr: 'तालुका रुग्णालय, दिंडोरी',
      hi: 'तालुका अस्पताल, दिंडोरी',
      en: 'Taluka Hospital, Dindori',
    },
    district: 'Nashik',
    location: 'Near Bus Stand, Dindori',
    contactNumber: '02557-221045',
    emergencyPhone: '108',
    totalActivePatients: 34,
  },
  {
    id: 'niphad',
    name: {
      mr: 'ग्रामीण रुग्णालय, निफाड',
      hi: 'ग्रामीण अस्पताल, निफाड',
      en: 'Rural Hospital, Niphad',
    },
    district: 'Nashik',
    location: 'Station Road, Niphad',
    contactNumber: '02555-242330',
    emergencyPhone: '108',
    totalActivePatients: 22,
  },
  {
    id: 'nashik_civil',
    name: {
      mr: 'जिल्हा सामान्य रुग्णालय, नाशिक (सिव्हिल)',
      hi: 'जिला सिविल अस्पताल, नाशिक',
      en: 'District Civil Hospital, Nashik',
    },
    district: 'Nashik',
    location: 'Trimbak Road, Nashik',
    contactNumber: '0253-2576106',
    emergencyPhone: '108 / 0253-2572038',
    totalActivePatients: 110,
  },
];

export const MOCK_DEPARTMENTS: Department[] = [
  {
    id: 'registration',
    name: { mr: 'नोंदणी व ट्रियाज', hi: 'पंजीकरण व प्राथमिक जांच', en: 'Registration & Triage' },
    hospitalId: 'sinnar',
    roomNumber: 'खोली क्र. १ (काउंटर १ व २)',
    doctorOrStaffName: 'श्री. गणेश आव्हाड (आरोग्य सेवक)',
    activeStaff: 2,
    avgConsultMins: 3,
    currentQueueLength: 4,
    currentServingToken: 'A-19',
    statusLevel: 'green',
    statusLabel: { mr: 'कमी गर्दी', hi: 'कम भीड़', en: 'Low Wait' },
  },
  {
    id: 'opd_1',
    name: { mr: 'सामान्य बाह्यरुग्ण (OPD 1)', hi: 'सामान्य ओपीडी 1', en: 'General Medicine OPD 1' },
    hospitalId: 'sinnar',
    roomNumber: 'खोली क्र. २',
    doctorOrStaffName: 'डॉ. सचिन पाटील (M.B.B.S)',
    activeStaff: 1,
    avgConsultMins: 8,
    currentQueueLength: 9,
    currentServingToken: 'A-08',
    statusLevel: 'red',
    statusLabel: { mr: 'जास्त गर्दी', hi: 'ज्यादा भीड़', en: 'High Wait' },
  },
  {
    id: 'opd_2',
    name: { mr: 'सामान्य बाह्यरुग्ण (OPD 2)', hi: 'सामान्य ओपीडी 2', en: 'General Medicine OPD 2' },
    hospitalId: 'sinnar',
    roomNumber: 'खोली क्र. ३',
    doctorOrStaffName: 'डॉ. प्रियांका देशमुख (M.D)',
    activeStaff: 1,
    avgConsultMins: 7,
    currentQueueLength: 3,
    currentServingToken: 'A-11',
    statusLevel: 'green',
    statusLabel: { mr: 'कमी गर्दी (मोकळे)', hi: 'कम भीड़ (उपलब्ध)', en: 'Low Wait (Available)' },
  },
  {
    id: 'lab',
    name: { mr: 'पॅथॉलॉजी लॅब (रक्त/लघवी)', hi: 'पैथोलॉजी लैब (रक्त/मूत्र)', en: 'Pathology Lab' },
    hospitalId: 'sinnar',
    roomNumber: 'खोली क्र. ५',
    doctorOrStaffName: 'श्रीमती अलका सोनवणे (लॅब टेक्निशियन)',
    activeStaff: 2,
    avgConsultMins: 5,
    currentQueueLength: 2,
    currentServingToken: 'L-05',
    statusLevel: 'green',
    statusLabel: { mr: 'कमी गर्दी', hi: 'कम भीड़', en: 'Low Wait' },
  },
  {
    id: 'xray',
    name: { mr: 'डिजिटल एक्स-रे विभाग', hi: 'डिजिटल एक्स-रे विभाग', en: 'Digital X-Ray / Imaging' },
    hospitalId: 'sinnar',
    roomNumber: 'खोली क्र. ६',
    doctorOrStaffName: 'श्री. राहुल जाधव (रेडिओग्राफर)',
    activeStaff: 1,
    avgConsultMins: 10,
    currentQueueLength: 4,
    currentServingToken: 'X-03',
    statusLevel: 'amber',
    statusLabel: { mr: 'थोडी गर्दी', hi: 'मध्यम भीड़', en: 'Moderate Wait' },
  },
  {
    id: 'report',
    name: { mr: 'रिपोर्ट वितरण केंद्र', hi: 'रिपोर्ट वितरण केंद्र', en: 'Report Dispatch Desk' },
    hospitalId: 'sinnar',
    roomNumber: 'खोली क्र. ७ (खिडकी)',
    doctorOrStaffName: 'श्री. संदीप वाघ',
    activeStaff: 1,
    avgConsultMins: 2,
    currentQueueLength: 1,
    currentServingToken: 'R-07',
    statusLevel: 'green',
    statusLabel: { mr: 'तातडीने मिळेल', hi: 'तुरंत मिलेगा', en: 'Immediate' },
  },
  {
    id: 'pharmacy',
    name: { mr: 'शासकीय मोफत औषधालय', hi: 'सरकारी मुफ्त फार्मेसी', en: 'Govt Free Pharmacy' },
    hospitalId: 'sinnar',
    roomNumber: 'काउंटर क्र. २',
    doctorOrStaffName: 'श्री. योगेश कातकाडे (फार्मासिस्ट)',
    activeStaff: 2,
    avgConsultMins: 3,
    currentQueueLength: 5,
    currentServingToken: 'P-14',
    statusLevel: 'amber',
    statusLabel: { mr: 'थोडी गर्दी', hi: 'मध्यम भीड़', en: 'Moderate Wait' },
  },
];

export const MOCK_SPECIALISTS: SpecialistDoctor[] = [
  {
    id: 'spec_eye_1',
    hospitalId: 'sinnar',
    name: 'डॉ. मिलींद देशमुख',
    specialty: 'नेत्ररोग तज्ज्ञ (मोतीबिंदू व चष्मा)',
    specialtyKey: 'eye',
    specialtyLabel: { mr: 'नेत्ररोग तज्ज्ञ', hi: 'नेत्र रोग विशेषज्ञ', en: 'Ophthalmology' },
    visitDays: ['Monday', 'Thursday'],
    visitDaysMr: ['सोमवार', 'गुरुवार'],
    visitDaysHi: ['सोमवार', 'गुरुवार'],
    timings: 'सकाळी ९:३० ते दुपारी १:३०',
    capacityPerDay: 25,
    nextAvailableDate: '2026-10-05',
    nextAvailableDayLabel: { mr: 'सोमवार, ५ ऑक्टोबर', hi: 'सोमवार, ५ अक्टूबर', en: 'Monday, Oct 5' },
    availableSlots: ['09:30 AM', '10:00 AM', '10:30 AM', '11:15 AM', '12:00 PM', '12:45 PM'],
    bookedSlotsCount: 19,
    cancelledDates: [],
  },
  {
    id: 'spec_ortho_1',
    hospitalId: 'sinnar',
    name: 'डॉ. विवेक जोशी',
    specialty: 'हाडांचे व मणक्यांचे तज्ज्ञ (Orthopedic)',
    specialtyKey: 'ortho',
    specialtyLabel: { mr: 'हाडांचे डॉक्टर', hi: 'हड्डी रोग विशेषज्ञ', en: 'Orthopedics' },
    visitDays: ['Wednesday', 'Saturday'],
    visitDaysMr: ['बुधवार', 'शनिवार'],
    visitDaysHi: ['बुधवार', 'शनिवार'],
    timings: 'सकाळी १०:०० ते दुपारी २:००',
    capacityPerDay: 20,
    nextAvailableDate: '2026-10-03',
    nextAvailableDayLabel: { mr: 'शनिवार, ३ ऑक्टोबर', hi: 'शनिवार, ३ अक्टूबर', en: 'Saturday, Oct 3' },
    availableSlots: ['10:00 AM', '10:45 AM', '11:30 AM', '01:00 PM'],
    bookedSlotsCount: 16,
    cancelledDates: [],
  },
  {
    id: 'spec_peds_1',
    hospitalId: 'sinnar',
    name: 'डॉ. रोहिणी कुलकर्णी',
    specialty: 'बालरोग व नवजात शिशु तज्ज्ञ',
    specialtyKey: 'peds',
    specialtyLabel: { mr: 'बालरोग तज्ज्ञ', hi: 'बाल रोग विशेषज्ञ', en: 'Pediatrics' },
    visitDays: ['Tuesday', 'Friday'],
    visitDaysMr: ['मंगळवार', 'शुक्रवार'],
    visitDaysHi: ['मंगलवार', 'शुक्रवार'],
    timings: 'दुपारी १२:०० ते ४:००',
    capacityPerDay: 30,
    nextAvailableDate: '2026-10-02',
    nextAvailableDayLabel: { mr: 'शुक्रवार, २ ऑक्टोबर', hi: 'शुक्रवार, २ अक्टूबर', en: 'Friday, Oct 2' },
    availableSlots: ['12:00 PM', '12:30 PM', '01:15 PM', '02:00 PM', '03:00 PM'],
    bookedSlotsCount: 22,
    cancelledDates: [],
  },
  {
    id: 'spec_gyn_1',
    hospitalId: 'sinnar',
    name: 'डॉ. स्नेहल पवार',
    specialty: 'स्त्रीरोग व प्रसूती तज्ज्ञ (Gynecologist)',
    specialtyKey: 'gyn',
    specialtyLabel: { mr: 'स्त्रीरोग तज्ज्ञ', hi: 'स्त्री रोग विशेषज्ञ', en: 'Gynecology' },
    visitDays: ['Monday', 'Wednesday', 'Friday'],
    visitDaysMr: ['सोमवार', 'बुधवार', 'शुक्रवार'],
    visitDaysHi: ['सोमवार', 'बुधवार', 'शुक्रवार'],
    timings: 'सकाळी ९:०० ते १:००',
    capacityPerDay: 35,
    nextAvailableDate: '2026-10-02',
    nextAvailableDayLabel: { mr: 'शुक्रवार, २ ऑक्टोबर', hi: 'शुक्रवार, २ अक्टूबर', en: 'Friday, Oct 2' },
    availableSlots: ['09:00 AM', '09:45 AM', '10:30 AM', '11:15 AM'],
    bookedSlotsCount: 28,
    cancelledDates: [],
  },
  {
    id: 'spec_ent_1',
    hospitalId: 'sinnar',
    name: 'डॉ. अरविंद गायकवाड',
    specialty: 'कान, नाक, घसा तज्ज्ञ (ENT Surgeon)',
    specialtyKey: 'ent',
    specialtyLabel: { mr: 'कान-नाक-घसा', hi: 'कान-नाक-गला', en: 'ENT' },
    visitDays: ['Tuesday', 'Thursday'],
    visitDaysMr: ['मंगळवार', 'गुरुवार'],
    visitDaysHi: ['मंगलवार', 'गुरुवार'],
    timings: 'सकाळी १०:०० ते १:००',
    capacityPerDay: 20,
    nextAvailableDate: '2026-10-06',
    nextAvailableDayLabel: { mr: 'मंगळवार, ६ ऑक्टोबर', hi: 'मंगलवार, ६ अक्टूबर', en: 'Tuesday, Oct 6' },
    availableSlots: ['10:00 AM', '10:30 AM', '11:30 AM', '12:15 PM'],
    bookedSlotsCount: 15,
    cancelledDates: [],
  },
  {
    id: 'spec_skin_1',
    hospitalId: 'sinnar',
    name: 'डॉ. मीना शिंदे',
    specialty: 'त्वचारोग व ऍलर्जी तज्ज्ञ (Dermatology)',
    specialtyKey: 'skin',
    specialtyLabel: { mr: 'त्वचारोग तज्ज्ञ', hi: 'त्वचा रोग विशेषज्ञ', en: 'Dermatology' },
    visitDays: ['Wednesday'],
    visitDaysMr: ['बुधवार'],
    visitDaysHi: ['बुधवार'],
    timings: 'दुपारी १:०० ते ५:००',
    capacityPerDay: 25,
    nextAvailableDate: '2026-10-07',
    nextAvailableDayLabel: { mr: 'बुधवार, ७ ऑक्टोबर', hi: 'बुधवार, ७ अक्टूबर', en: 'Wednesday, Oct 7' },
    availableSlots: ['01:00 PM', '01:45 PM', '02:30 PM', '03:30 PM'],
    bookedSlotsCount: 20,
    cancelledDates: [],
  },
  {
    id: 'spec_eye_2',
    hospitalId: 'igatpuri',
    name: 'डॉ. जयेश परदेशी',
    specialty: 'नेत्ररोग व दृष्टिदोष तज्ज्ञ',
    specialtyKey: 'eye',
    specialtyLabel: { mr: 'नेत्ररोग तज्ज्ञ', hi: 'नेत्र रोग विशेषज्ञ', en: 'Ophthalmology' },
    visitDays: ['Tuesday', 'Friday'],
    visitDaysMr: ['मंगळवार', 'शुक्रवार'],
    visitDaysHi: ['मंगलवार', 'शुक्रवार'],
    timings: 'सकाळी १०:०० ते दुपारी २:००',
    capacityPerDay: 25,
    nextAvailableDate: '2026-10-02',
    nextAvailableDayLabel: { mr: 'शुक्रवार, २ ऑक्टोबर', hi: 'शुक्रवार, २ अक्टूबर', en: 'Friday, Oct 2' },
    availableSlots: ['10:00 AM', '11:00 AM', '12:00 PM'],
    bookedSlotsCount: 18,
    cancelledDates: [],
  },
  {
    id: 'spec_ortho_2',
    hospitalId: 'dindori',
    name: 'डॉ. अभय कुलकर्णी',
    specialty: 'ऑर्थोपेडिक व सांधेदुखी तज्ज्ञ',
    specialtyKey: 'ortho',
    specialtyLabel: { mr: 'हाडांचे डॉक्टर', hi: 'हड्डी रोग विशेषज्ञ', en: 'Orthopedics' },
    visitDays: ['Monday', 'Thursday'],
    visitDaysMr: ['सोमवार', 'गुरुवार'],
    visitDaysHi: ['सोमवार', 'गुरुवार'],
    timings: 'सकाळी ९:०० ते १:००',
    capacityPerDay: 20,
    nextAvailableDate: '2026-10-05',
    nextAvailableDayLabel: { mr: 'सोमवार, ५ ऑक्टोबर', hi: 'सोमवार, ५ अक्टूबर', en: 'Monday, Oct 5' },
    availableSlots: ['09:30 AM', '10:30 AM', '11:30 AM'],
    bookedSlotsCount: 12,
    cancelledDates: [],
  },
];

export const MOCK_PATIENTS: PatientJourney[] = [
  // 1. MAIN HERO PATIENT FOR DEMO (SHOWS PARALLEL SCHEDULING USP)
  {
    id: 'patient_01',
    tokenNumber: 'A-12',
    patientName: 'सखाराम बापू शिंदे (Sakharam Shinde)',
    mobile: '9822014589',
    age: 62,
    gender: 'M',
    language: 'mr',
    hospitalId: 'sinnar',
    priorityLevel: 'senior',
    priorityScore: 250,
    priorityFlags: { isEmergency: false, isPregnant: false, isSenior: true },
    symptoms: ['छातीत दुखणे / खोकला', 'ताप / अंगदुखी'],
    departmentPreference: 'opd_1',
    currentStepIndex: 2, // At Lab (parallel scheduled ahead of Doctor)
    isParallelScheduled: true,
    parallelReason: {
      mr: 'डॉक्टर १ कडे जास्त गर्दी आहे (४० मि.). आधी लॅबमध्ये रक्त द्या, तोपर्यंत डॉक्टर मोकळे होतील आणि रिपोर्टही तयार असेल!',
      hi: 'डॉक्टर १ पर ज्यादा भीड़ है (४० मि.). पहले लैब में रक्त दें, तब तक डॉक्टर खाली होंगे और रिपोर्ट भी तैयार होगी!',
      en: 'Doctor 1 queue is long (40 min). Visit Lab first so results are ready when the doctor calls you!',
    },
    totalEstimatedWaitMinutes: 55,
    status: 'in_lab',
    checkInTime: '09:40 AM',
    lastUpdated: '10:05 AM',
    activeAlert: {
      id: 'alt_01',
      type: 'info',
      message: {
        mr: 'समांतर रांग सक्रिय: लॅब खोली क्र. ५ मध्ये लगेच जा.',
        hi: 'समानांतर कतार सक्रिय: लैब कमरा क्र. ५ में तुरंत जाएं।',
        en: 'Parallel routing active: Please proceed directly to Lab Room 5.',
      },
      timestamp: '10:05 AM',
    },
    steps: [
      {
        id: 'step_1',
        departmentId: 'registration',
        departmentName: { mr: 'नोंदणी व ट्रियाज', hi: 'पंजीकरण', en: 'Registration' },
        counterNumber: 'काउंटर १',
        estimatedWaitMinutes: 5,
        actualDurationMinutes: 4,
        status: 'completed',
        startedAt: '09:40 AM',
        completedAt: '09:44 AM',
      },
      {
        id: 'step_2',
        departmentId: 'doctor',
        departmentName: { mr: 'डॉक्टर तपासणी (OPD 1)', hi: 'डॉक्टर परामर्श (OPD 1)', en: 'Doctor Consultation (OPD 1)' },
        counterNumber: 'खोली क्र. २ (डॉ. सचिन पाटील)',
        estimatedWaitMinutes: 35,
        status: 'pending',
        notes: 'लॅब रिपोर्ट आल्यावर प्राधान्याने नंबर लागेल.',
      },
      {
        id: 'step_3',
        departmentId: 'lab',
        departmentName: { mr: 'पॅथॉलॉजी लॅब (CBC व शुगर)', hi: 'पैथोलॉजी लैब', en: 'Pathology Lab' },
        counterNumber: 'खोली क्र. ५',
        estimatedWaitMinutes: 8,
        status: 'in_progress',
        isParallelShifted: true,
        notes: 'समांतर शेड्युलिंग: आधी लॅब तपासणी सुरू आहे.',
      },
      {
        id: 'step_4',
        departmentId: 'report',
        departmentName: { mr: 'डिजिटल रिपोर्ट', hi: 'डिजिटल रिपोर्ट', en: 'Digital Lab Report' },
        counterNumber: 'सिस्टममध्ये थेट डॉक्टरांना पाठवला जाईल',
        estimatedWaitMinutes: 5,
        status: 'pending',
      },
      {
        id: 'step_5',
        departmentId: 'pharmacy',
        departmentName: { mr: 'मोफत औषधालय', hi: 'मुफ्त फार्मेसी', en: 'Pharmacy Dispensing' },
        counterNumber: 'काउंटर क्र. २',
        estimatedWaitMinutes: 10,
        status: 'pending',
      },
    ],
  },

  // 2. PATIENT AT PHARMACY (WITH DIGITAL PRESCRIPTION AUTO-HANDOFF)
  {
    id: 'patient_02',
    tokenNumber: 'A-05',
    patientName: 'सुनिताबाई रामभाऊ जाधव (Sunita Jadhav)',
    mobile: '9423188720',
    age: 28,
    gender: 'F',
    language: 'mr',
    hospitalId: 'sinnar',
    priorityLevel: 'pregnant',
    priorityScore: 500,
    priorityFlags: { isEmergency: false, isPregnant: true, isSenior: false },
    symptoms: ['उलटी / चक्कर'],
    departmentPreference: 'opd_2',
    currentStepIndex: 4, // At Pharmacy
    isParallelScheduled: false,
    totalEstimatedWaitMinutes: 8,
    status: 'in_pharmacy',
    checkInTime: '09:15 AM',
    lastUpdated: '10:10 AM',
    activeAlert: {
      id: 'alt_02',
      type: 'success',
      message: {
        mr: 'औषधे तयार आहेत! काउंटर २ वर त्वरित औषधे घ्या.',
        hi: 'दवाएं तैयार हैं! काउंटर २ पर तुरंत दवाएं प्राप्त करें।',
        en: 'Medicines ready! Please collect from Pharmacy Counter 2.',
      },
      timestamp: '10:10 AM',
    },
    steps: [
      {
        id: 'step_21',
        departmentId: 'registration',
        departmentName: { mr: 'नोंदणी', hi: 'पंजीकरण', en: 'Registration' },
        counterNumber: 'काउंटर १',
        estimatedWaitMinutes: 3,
        actualDurationMinutes: 3,
        status: 'completed',
      },
      {
        id: 'step_22',
        departmentId: 'doctor',
        departmentName: { mr: 'डॉक्टर तपासणी (OPD 2)', hi: 'डॉक्टर परामर्श', en: 'Doctor Consultation' },
        counterNumber: 'खोली क्र. ३',
        estimatedWaitMinutes: 10,
        actualDurationMinutes: 8,
        status: 'completed',
        notes: 'डॉक्टरांनी डिजिटल औषधे पाठवली आहेत.',
      },
      {
        id: 'step_23',
        departmentId: 'lab',
        departmentName: { mr: 'तपासणी', hi: 'जांच', en: 'Lab Test' },
        counterNumber: 'लागू नाही',
        estimatedWaitMinutes: 0,
        status: 'skipped',
      },
      {
        id: 'step_24',
        departmentId: 'report',
        departmentName: { mr: 'रिपोर्ट', hi: 'रिपोर्ट', en: 'Report' },
        counterNumber: 'लागू नाही',
        estimatedWaitMinutes: 0,
        status: 'skipped',
      },
      {
        id: 'step_25',
        departmentId: 'pharmacy',
        departmentName: { mr: 'मोफत औषधालय', hi: 'मुफ्त फार्मेसी', en: 'Pharmacy' },
        counterNumber: 'काउंटर क्र. २',
        estimatedWaitMinutes: 4,
        status: 'in_progress',
        notes: 'औषध पॅक झाले आहे. टोकन बोलावले आहे.',
      },
    ],
  },

  // 3. EMERGENCY PATIENT
  {
    id: 'patient_03',
    tokenNumber: 'E-01',
    patientName: 'आनंदा गणपत पाटील (Ananda Patil)',
    mobile: '9890123999',
    age: 45,
    gender: 'M',
    language: 'mr',
    hospitalId: 'sinnar',
    priorityLevel: 'emergency',
    priorityScore: 1000,
    priorityFlags: { isEmergency: true, isPregnant: false, isSenior: false },
    symptoms: ['छातीत असह्य वेदना / श्वास लागणे'],
    departmentPreference: 'opd_1',
    currentStepIndex: 1, // With Doctor directly
    isParallelScheduled: false,
    totalEstimatedWaitMinutes: 0,
    status: 'in_consultation',
    checkInTime: '10:02 AM',
    lastUpdated: '10:04 AM',
    activeAlert: {
      id: 'alt_03',
      type: 'action',
      message: {
        mr: 'इमर्जन्सी रुग्ण: तातडीने डॉक्टर खोली २ मध्ये उपचार सुरू.',
        hi: 'आपातकालीन मरीज: तुरंत कमरा २ में उपचार जारी।',
        en: 'Emergency patient: Immediate triage at Doctor Room 2.',
      },
      timestamp: '10:04 AM',
    },
    steps: [
      {
        id: 'step_31',
        departmentId: 'registration',
        departmentName: { mr: 'इमर्जन्सी नोंदणी', hi: 'आपातकालीन पंजीकरण', en: 'Emergency Triage' },
        counterNumber: 'ट्रियाज टेबल',
        estimatedWaitMinutes: 0,
        actualDurationMinutes: 1,
        status: 'completed',
      },
      {
        id: 'step_32',
        departmentId: 'doctor',
        departmentName: { mr: 'डॉक्टर तपासणी (तातडीने)', hi: 'डॉक्टर परामर्श', en: 'Doctor Consultation (Immediate)' },
        counterNumber: 'खोली क्र. २',
        estimatedWaitMinutes: 0,
        status: 'in_progress',
      },
      {
        id: 'step_33',
        departmentId: 'lab',
        departmentName: { mr: 'तातडीचे ईसीजी व ट्रोपोनिन', hi: 'ईसीजी जांच', en: 'Stat ECG & Troponin' },
        counterNumber: 'खोली क्र. ५',
        estimatedWaitMinutes: 5,
        status: 'pending',
      },
      {
        id: 'step_34',
        departmentId: 'report',
        departmentName: { mr: 'रिपोर्ट', hi: 'रिपोर्ट', en: 'Report' },
        counterNumber: 'तातडीने',
        estimatedWaitMinutes: 3,
        status: 'pending',
      },
      {
        id: 'step_35',
        departmentId: 'pharmacy',
        departmentName: { mr: 'इमर्जन्सी औषधे', hi: 'आपातकालीन दवाएं', en: 'Emergency Meds' },
        counterNumber: 'काउंटर क्र. २',
        estimatedWaitMinutes: 2,
        status: 'pending',
      },
    ],
  },

  // 4. NORMAL PATIENT IN OPD QUEUE
  {
    id: 'patient_04',
    tokenNumber: 'A-15',
    patientName: 'मंगला ज्ञानेश्वर बोरसे (Mangala Borse)',
    mobile: '9158334411',
    age: 38,
    gender: 'F',
    language: 'mr',
    hospitalId: 'sinnar',
    priorityLevel: 'normal',
    priorityScore: 100,
    priorityFlags: { isEmergency: false, isPregnant: false, isSenior: false },
    symptoms: ['पोटदुखी / उलटी'],
    departmentPreference: 'opd_2',
    currentStepIndex: 1, // Waiting for OPD 2
    isParallelScheduled: false,
    totalEstimatedWaitMinutes: 25,
    status: 'waiting',
    checkInTime: '09:50 AM',
    lastUpdated: '09:52 AM',
    steps: [
      {
        id: 'step_41',
        departmentId: 'registration',
        departmentName: { mr: 'नोंदणी', hi: 'पंजीकरण', en: 'Registration' },
        counterNumber: 'काउंटर २',
        estimatedWaitMinutes: 4,
        actualDurationMinutes: 3,
        status: 'completed',
      },
      {
        id: 'step_42',
        departmentId: 'doctor',
        departmentName: { mr: 'डॉक्टर तपासणी (OPD 2)', hi: 'डॉक्टर परामर्श (OPD 2)', en: 'Doctor Consultation (OPD 2)' },
        counterNumber: 'खोली क्र. ३',
        estimatedWaitMinutes: 14,
        status: 'in_progress',
        notes: '२ रुग्ण पुढे आहेत.',
      },
      {
        id: 'step_43',
        departmentId: 'pharmacy',
        departmentName: { mr: 'मोफत औषधालय', hi: 'मुफ्त फार्मेसी', en: 'Pharmacy' },
        counterNumber: 'काउंटर क्र. २',
        estimatedWaitMinutes: 8,
        status: 'pending',
      },
    ],
  },

  // 5. SENIOR PATIENT JUST CHECKED IN
  {
    id: 'patient_05',
    tokenNumber: 'A-18',
    patientName: 'तुकाराम विठोबा गावंडे (Tukaram Gawande)',
    mobile: '9763214500',
    age: 68,
    gender: 'M',
    language: 'mr',
    hospitalId: 'sinnar',
    priorityLevel: 'senior',
    priorityScore: 250,
    priorityFlags: { isEmergency: false, isPregnant: false, isSenior: true },
    symptoms: ['हात-पाय / हाडांचे दुखणे'],
    departmentPreference: 'opd_1',
    currentStepIndex: 0, // Registration
    isParallelScheduled: false,
    totalEstimatedWaitMinutes: 40,
    status: 'waiting',
    checkInTime: '10:08 AM',
    lastUpdated: '10:08 AM',
    steps: [
      {
        id: 'step_51',
        departmentId: 'registration',
        departmentName: { mr: 'नोंदणी व ट्रियाज', hi: 'पंजीकरण', en: 'Registration' },
        counterNumber: 'काउंटर क्र. १',
        estimatedWaitMinutes: 3,
        status: 'in_progress',
      },
      {
        id: 'step_52',
        departmentId: 'doctor',
        departmentName: { mr: 'डॉक्टर तपासणी (OPD 1)', hi: 'डॉक्टर परामर्श', en: 'Doctor Consultation' },
        counterNumber: 'खोली क्र. २',
        estimatedWaitMinutes: 25,
        status: 'pending',
      },
      {
        id: 'step_53',
        departmentId: 'xray',
        departmentName: { mr: 'गुडघा व सांधे एक्स-रे', hi: 'एक्स-रे', en: 'Joint X-Ray' },
        counterNumber: 'खोली क्र. ६',
        estimatedWaitMinutes: 10,
        status: 'pending',
      },
      {
        id: 'step_54',
        departmentId: 'pharmacy',
        departmentName: { mr: 'मोफत औषधालय', hi: 'मुफ्त फार्मेसी', en: 'Pharmacy' },
        counterNumber: 'काउंटर क्र. २',
        estimatedWaitMinutes: 8,
        status: 'pending',
      },
    ],
  },
];

export const MOCK_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx_01',
    patientId: 'patient_02',
    patientName: 'सुनिताबाई रामभाऊ जाधव',
    tokenNumber: 'A-05',
    doctorName: 'डॉ. प्रियांका देशमुख (OPD 2)',
    items: [
      { name: 'टॅब. फॉलिक ॲसिड (Folic Acid 5mg)', dosage: '१ गोळी रोज सकाळी', duration: '३० दिवस', instructions: 'जेवणानंतर' },
      { name: 'टॅब. कॅल्शियम व व्हिटॅमिन D3', dosage: '१ गोळी रोज दुपारी', duration: '३० दिवस', instructions: 'दुधासोबत' },
      { name: 'टॅब. डोमपेरिडोन (उलटीसाठी)', dosage: '१ गोळी सकाळी उपाशीपोटी', duration: '५ दिवस', instructions: 'गरज भासल्यास' },
    ],
    status: 'ready',
    counterNumber: 'काउंटर क्र. २',
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    readyAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 22 * 60 * 1000).toISOString(),
  },
  {
    id: 'rx_02',
    patientId: 'patient_01',
    patientName: 'सखाराम बापू शिंदे',
    tokenNumber: 'A-12',
    doctorName: 'डॉ. सचिन पाटील (OPD 1)',
    items: [
      { name: 'टॅब. पॅरासिटामॉल ६५० (Paracetamol 650mg)', dosage: '१ गोळी दिवसातून ३ वेळा', duration: '३ दिवस', instructions: 'तापासाठी, जेवणानंतर' },
      { name: 'सिरप कफ रिलिफ (Cough Syrup)', dosage: '२ चमचे रात्री झोपताना', duration: '५ दिवस', instructions: 'कोमट पाण्यासोबत' },
    ],
    status: 'preparing',
    counterNumber: 'काउंटर क्र. २',
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    id: 'rx_03',
    patientId: 'patient_07',
    patientName: 'दगडू तुळशीराम खैरनार',
    tokenNumber: 'A-03',
    doctorName: 'डॉ. सचिन पाटील',
    items: [
      { name: 'टॅब. ॲम्लोडिपिन ५ मिली (BP)', dosage: '१ गोळी सकाळी', duration: '३० दिवस', instructions: 'नियमित घ्या' },
      { name: 'टॅब. ॲटोर्व्हास्टॅटिन १० मिली', dosage: '१ गोळी रात्री', duration: '३० दिवस', instructions: 'जेवणानंतर' },
    ],
    status: 'dispensed',
    counterNumber: 'काउंटर क्र. २',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    readyAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
];

export const MOCK_SMS_ALERTS: SMSAlert[] = [
  {
    id: 'sms_01',
    mobile: '9822014589',
    patientName: 'सखाराम बापू शिंदे',
    tokenNumber: 'A-12',
    text: '[सिन्नर रुग्णालय] आपला टोकन क्र. A-12 आहे. डॉक्टर रांग जास्त असल्याने वेळेच्या बचतीसाठी आधी खोली क्र. ५ (लॅब) मध्ये रक्त तपासणीसाठी जा.',
    timestamp: '10:05 AM',
    type: 'parallel_shift',
    read: true,
  },
  {
    id: 'sms_02',
    mobile: '9423188720',
    patientName: 'सुनिताबाई रामभाऊ जाधव',
    tokenNumber: 'A-05',
    text: '[सिन्नर रुग्णालय] टोकन A-05: आपली औषधे तयार आहेत. कृपया पुढील ३० मिनिटांत फार्मसी काउंटर क्र. २ वरून मोफत औषधे गोळा करा.',
    timestamp: '10:10 AM',
    type: 'pharmacy_ready',
    read: true,
  },
  {
    id: 'sms_03',
    mobile: '9890123999',
    patientName: 'आनंदा गणपत पाटील',
    tokenNumber: 'E-01',
    text: '[सिन्नर रुग्णालय] तातडीचे टोकन E-01: थेट डॉक्टर खोली क्र. २ मध्ये जा. प्राधान्य उपचार सुरू आहेत.',
    timestamp: '10:02 AM',
    type: 'turn_alert',
    read: true,
  },
];
